### ISSUE TITLE
Editing fits drag and drop doesn't seem to work.

### ISSUE THREAD

**Issue by Sysape** [BattleClinic/BattleClinic.com-public#12]
http://forum.battleclinic.com/index.php?topic=187568.new#new

someone mentioned this here and I tested it on one of my fits.

http://eve.battleclinic.com/ship_loadout.php?action=edit&id=71627 and when I try and drag and drop it I get a no logo like http://www.clipartbest.com/cliparts/pi5/9x6/pi59x64iB.png hovering and dragging modules around does nothing, Whether it's over other modules or the bin.

**Comment by MrCue** [comment]
This should be resolved now
