### ISSUE TITLE
There was an error loading this page. 

### ISSUE THREAD

**Issue by westtell4** [BattleClinic/BattleClinic.com-public#14]
I keep getting There was an error loading this page.  on Everything that i click on the website.except for the fourms everything else  has the error

**Comment by MrCue** [comment]
Please provide a link to pages this is happening on for you.

**Comment by westtell4** [comment]
http://eve.battleclinic.com/    http://eve.battleclinic.com/killboard/index.php       http://evemon.battleclinic.com/index.php 
 http://eve.battleclinic.com/browse_loadouts.php# there is every URL that it is happening on

**Comment by westtell4** [comment]
![battleclinic](https://cloud.githubusercontent.com/assets/11027099/6218936/919923f6-b5f1-11e4-92da-d536d8bab1ba.JPG)

**Comment by westtell4** [comment]
This problem is solved i had to clear my browser data. and that seemed to stop the error from happening i don't know why it was doing that but i was also having network/router problems at the time that i was not aware of
