### ISSUE TITLE
Duplicate Character and KMs not posting

### ISSUE THREAD

**Issue by rqtbal** [BattleClinic/BattleClinic.com-public#2]
There are two of the same character on BC.

Filthy Gorgeous and filthy Gorgeous are the same, and it's apparently screwing things up.

Also, this character's KMs have not updated since 27 December, despite having manually input them. (Yes, I was cognizant of spaces)

**Comment by ColinVaughan** [comment]
It sounds like I'm having a similar issue.

Dylan Reem and dylan Reem are the same but killmails haven't updated since early February.
