### ISSUE TITLE
Fit comments sporadically can't be viewed

### ISSUE THREAD

**Issue by acdevlin** [BattleClinic/BattleClinic.com-public#22]
Having a strange problem where I can't always see the comments on a fit, and I can't find any information as to why.

First example is a fit where I'm able to view the sole comment properly:
![bc_can_see_comments](https://cloud.githubusercontent.com/assets/2645977/6454011/7166b0d6-c0f9-11e4-9998-7c385ded7f95.PNG)

I'm able to view some other fits with more than 1 comment properly as well, though this next example is a fit where I'm unable to view the two comments:
![bc_cant_see_comments](https://cloud.githubusercontent.com/assets/2645977/6454017/8b19173a-c0f9-11e4-9eea-da14314abfb1.PNG)

The only possible explanation I can see is the first fit has a neutral score of +0/-0 while the latter has a negative score of +0/-1...but preventing users from seeing comments on negatively-rated fits is just silly so that couldn't be the case, right?

Help would be greatly appreciated. This bug is annoying and makes discussion about fits that much more challenging to accomplish.

**Comment by MrCue** [comment]
can you link to the two pages in your example so i can have a look?

There is nothing in the code that would prevent you from seeing/commenting on negatively rated fits.

This is the one you can't seen the comments on?, but i can.
http://eve.battleclinic.com/view_loadout.php?id=72064

**Comment by acdevlin** [comment]
Yup, the "surprise merlin" you linked is the one I can't see comments on. Very interesting that you are able to...

The one I can see comments on is http://eve.battleclinic.com/view_loadout.php?id=72065 

Bit more info about my setup:
- Google Chrome
- Using AdBlock and ScriptNo addons, but every script on BattleClinic is allowed
- Windows 7 Home Edition, though that probably shouldn't make a difference

**Comment by MrCue** [comment]
It should be fixed now.

It was actually a private loadout but its permissions were all wrong.

**Comment by acdevlin** [comment]
Awesome, thanks for the quick resolution!
