### ISSUE TITLE
kills do not post

### ISSUE THREAD

**Issue by madeintheussr** [BattleClinic/BattleClinic.com-public#23]
When posting kills, at first, it used to take 12-24 hours for posted kill to appear on the killboard. Recent 8 kills that I have posted, have not showed after more then 24 hours.

If I am correct, kills should post instantly.

Character in question:

http://eve.battleclinic.com/killboard/combat_record.php?type=pilot&name=MECH+1000

some of the kills that I have posted more then 24 hours ago are:

http://public-crest.eveonline.com/killmails/46205183/c286f35a9987ea2f90935dca966520b775696a80/

http://public-crest.eveonline.com/killmails/46205297/07d051024b028168c2f1e02f1e57e4b05bd80d23/

those are just 2 examples, if you need all of the kills that are missing, I would have to provide them at a later time when I have access to EVE client, writing this from work computer @ the office.

**Comment by madeintheussr** [comment]
Update: out of 8 kills i mentioned originally, all have now posted (some 30 hours later) except for one.

http://public-crest.eveonline.com/killmails/46205297/07d051024b028168c2f1e02f1e57e4b05bd80d23/

Its #2 in the timeline, so kills before and kills after this one posted now.

**Comment by MrCue** [comment]
The backlog of kills has finished processing, your kills should post quickly again.
