### ISSUE TITLE
Main loadouts page seems to stop in July.

### ISSUE THREAD

**Issue by Sysape** [BattleClinic/BattleClinic.com-public#30]
http://eve.battleclinic.com/browse_loadouts.php

The latest fit is July 19, 2015, 09:07:48 pm and I know many fits have been posted since then.

**Comment by acdevlin** [comment]
+1, noticed this myself earlier and thought I was going crazy.

Screencap: http://i.imgur.com/GEHyLJC.jpg

No filters are applied. Fits sorted by date. Tried relogging and it had no effect.

**Comment by MrCue** [comment]
This should be resolved now

**Comment by acdevlin** [comment]
Confirm, it's fixed for me. Thanks Cue!

**Comment by Sysape** [comment]
Yup looks good to me. :D
