### ISSUE TITLE
Associates is meaningless and empty on Corp KB page

### ISSUE THREAD

**Issue by Sysape** [BattleClinic/BattleClinic.com-public#5]
The Associates tab isn't filled in, also not very useful intel. 

Rankings tab was good, please re-instate a tab with Rankings for pilots in the corp.

Likewise on the Alliance tab Associates should be a corp rankings list.

**Comment by MrCue** [comment]
I've got an issue open to address this.

The Associates tab, will be replaced by Pilots list on the corp view, and with corporations on the Alliance/Faction views.
